// Code generated DO NOT EDIT. (@generated)

package database

import (
	"time"
	"nja/pkg/ogame"
)
type BotID int64
type BotPlanet struct {
	ID int64
	Idx int64
	BotID BotID
	BrainMode int64
	EvacuationMode int64
	PreferredEvacuationDestination ogame.CelestialID
	Producer bool
	Exporter bool
	Importer bool
	Galaxy int64
	System int64
	Position int64
	PlanetType ogame.CelestialType
	PlanetID ogame.CelestialID
	Name string
	Diameter int64
	Img string
	FieldsBuilt int64
	FieldsTotal int64
	TemperatureMin int64
	TemperatureMax int64
	MetalMineSetting int64
	CrystalMineSetting int64
	DeuteriumSynthesizerSetting int64
	SolarPlantSetting int64
	FusionReactorSetting int64
	SolarSatelliteSetting int64
	CrawlerSetting int64
	ResourceSettingsUpdatedAt *time.Time
	Metal int64
	Crystal int64
	Deuterium int64
	Energy int64
	ResourcesUpdatedAt *time.Time
	MetalMine int64
	CrystalMine int64
	DeuteriumSynthesizer int64
	SolarPlant int64
	FusionReactor int64
	MetalStorage int64
	CrystalStorage int64
	DeuteriumTank int64
	ShieldedMetalDen int64
	UndergroundCrystalDen int64
	SeabedDeuteriumDen int64
	SuppliesUpdatedAt *time.Time
	AllianceDepot int64
	RoboticsFactory int64
	Shipyard int64
	ResearchLab int64
	MissileSilo int64
	NaniteFactory int64
	Terraformer int64
	SpaceDock int64
	LunarBase int64
	SensorPhalanx int64
	JumpGate int64
	FacilitiesUpdatedAt *time.Time
	RocketLauncher int64
	LightLaser int64
	HeavyLaser int64
	GaussCannon int64
	IonCannon int64
	PlasmaTurret int64
	SmallShieldDome int64
	LargeShieldDome int64
	AntiBallisticMissiles int64
	InterplanetaryMissiles int64
	DefensesUpdatedAt *time.Time
	LifeformType ogame.LifeformType
	ResidentialSector int64
	BiosphereFarm int64
	ResearchCentre int64
	AcademyOfSciences int64
	NeuroCalibrationCentre int64
	HighEnergySmelting int64
	FoodSilo int64
	FusionPoweredProduction int64
	Skyscraper int64
	BiotechLab int64
	Metropolis int64
	PlanetaryShield int64
	MeditationEnclave int64
	CrystalFarm int64
	RuneTechnologium int64
	RuneForge int64
	Oriktorium int64
	MagmaForge int64
	DisruptionChamber int64
	Megalith int64
	CrystalRefinery int64
	DeuteriumSynthesiser int64
	MineralResearchCentre int64
	AdvancedRecyclingPlant int64
	AssemblyLine int64
	FusionCellFactory int64
	RoboticsResearchCentre int64
	UpdateNetwork int64
	QuantumComputerCentre int64
	AutomatisedAssemblyCentre int64
	HighPerformanceTransformer int64
	MicrochipAssemblyLine int64
	ProductionAssemblyHall int64
	HighPerformanceSynthesiser int64
	ChipMassProduction int64
	NanoRepairBots int64
	Sanctuary int64
	AntimatterCondenser int64
	VortexChamber int64
	HallsOfRealisation int64
	ForumOfTranscendence int64
	AntimatterConvector int64
	CloningLaboratory int64
	ChrysalisAccelerator int64
	BioModifier int64
	PsionicModulator int64
	ShipManufacturingHall int64
	SupraRefractor int64
	LfBuildingsUpdatedAt *time.Time
	IntergalacticEnvoys *int64
	HighPerformanceExtractors *int64
	FusionDrives *int64
	StealthFieldGenerator *int64
	OrbitalDen *int64
	ResearchAI *int64
	HighPerformanceTerraformer *int64
	EnhancedProductionTechnologies *int64
	LightFighterMkII *int64
	CruiserMkII *int64
	ImprovedLabTechnology *int64
	PlasmaTerraformer *int64
	LowTemperatureDrives *int64
	BomberMkII *int64
	DestroyerMkII *int64
	BattlecruiserMkII *int64
	RobotAssistants *int64
	Supercomputer *int64
	VolcanicBatteries *int64
	AcousticScanning *int64
	HighEnergyPumpSystems *int64
	CargoHoldExpansionCivilianShips *int64
	MagmaPoweredProduction *int64
	GeothermalPowerPlants *int64
	DepthSounding *int64
	IonCrystalEnhancementHeavyFighter *int64
	ImprovedStellarator *int64
	HardenedDiamondDrillHeads *int64
	SeismicMiningTechnology *int64
	MagmaPoweredPumpSystems *int64
	IonCrystalModules *int64
	OptimisedSiloConstructionMethod *int64
	DiamondEnergyTransmitter *int64
	ObsidianShieldReinforcement *int64
	RuneShields *int64
	RocktalCollectorEnhancement *int64
	CatalyserTechnology *int64
	PlasmaDrive *int64
	EfficiencyModule *int64
	DepotAI *int64
	GeneralOverhaulLightFighter *int64
	AutomatedTransportLines *int64
	ImprovedDroneAI *int64
	ExperimentalRecyclingTechnology *int64
	GeneralOverhaulCruiser *int64
	SlingshotAutopilot *int64
	HighTemperatureSuperconductors *int64
	GeneralOverhaulBattleship *int64
	ArtificialSwarmIntelligence *int64
	GeneralOverhaulBattlecruiser *int64
	GeneralOverhaulBomber *int64
	GeneralOverhaulDestroyer *int64
	ExperimentalWeaponsTechnology *int64
	MechanGeneralEnhancement *int64
	HeatRecovery *int64
	SulphideProcess *int64
	PsionicNetwork *int64
	TelekineticTractorBeam *int64
	EnhancedSensorTechnology *int64
	NeuromodalCompressor *int64
	NeuroInterface *int64
	InterplanetaryAnalysisNetwork *int64
	OverclockingHeavyFighter *int64
	TelekineticDrive *int64
	SixthSense *int64
	Psychoharmoniser *int64
	EfficientSwarmIntelligence *int64
	OverclockingLargeCargo *int64
	GravitationSensors *int64
	OverclockingBattleship *int64
	PsionicShieldMatrix *int64
	KaeleshDiscovererEnhancement *int64
	LfResearchesUpdatedAt *time.Time
	SmallCargo int64
	LargeCargo int64
	LightFighter int64
	HeavyFighter int64
	Cruiser int64
	Battleship int64
	ColonyShip int64
	Recycler int64
	EspionageProbe int64
	Bomber int64
	SolarSatellite int64
	Destroyer int64
	Deathstar int64
	Battlecruiser int64
	Crawler int64
	Reaper int64
	Pathfinder int64
	ShipsUpdatedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	RepatriateActive bool
	RepatriateDestination ogame.CelestialID
	RepatriateMinimumDeuterium int64
	RepatriateMetal bool
	RepatriateCrystal bool
	RepatriateDeuterium bool
	SleepModeActive bool
	SleepModeDestination ogame.CelestialID
}
func (BotPlanet) ByID(param1 ogame.ID) int64 { panic("not implemented") }
func (BotPlanet) Coordinate() ogame.Coordinate { panic("not implemented") }
func (BotPlanet) GetDefenses() ogame.DefensesInfos { panic("not implemented") }
func (BotPlanet) GetFacilities() ogame.Facilities { panic("not implemented") }
func (BotPlanet) GetLfBuildings() ogame.LfBuildings { panic("not implemented") }
func (BotPlanet) GetLfResearches() ogame.LfResearches { panic("not implemented") }
func (BotPlanet) GetResourceBuildings() ogame.ResourcesBuildings { panic("not implemented") }
func (BotPlanet) GetResourceSettings() ogame.ResourceSettings { panic("not implemented") }
func (BotPlanet) GetShips() ogame.ShipsInfos { panic("not implemented") }
func (BotPlanet) GetTemperature() ogame.Temperature { panic("not implemented") }
func (BotPlanet) IsCrystalStorageFull() bool { panic("not implemented") }
func (BotPlanet) IsDeuteriumTankFull() bool { panic("not implemented") }
func (BotPlanet) IsMetalStorageFull() bool { panic("not implemented") }
type FarmSession struct {
	ID int64
	BotID BotID
	State string
	PlanetID ogame.CelestialID
	RangeGalaxy int64
	RangeFrom int64
	RangeTo int64
	NbProbes int64
	PctCargo int64
	CreatedAt time.Time
	MinimumResourcesToAttack int64
	MinimumDefensesToIgnore int64
	MinimumMetalStorage int64
	MinimumCrystalStorage int64
	MinimumDeuteriumTank int64
	MinimumPlayerRank int64
	MinimumPointsToAttack int64
	TotalTargets int64
	EspionageProbeRaids bool
	Phase int64
	Progress int64
	ProgressAttacks int64
	FarmType int64
	FuelConsumption int64
	MetalRatio float64
	CrystalRatio float64
	DeuteriumRatio float64
	FarmSpeed ogame.Speed
	FastAttacking bool
	AttackPlayersWithDefenses bool
	IgnoreActivity bool
	UsePathfinders bool
	SkipAfter int64
	AttackFromNearestPlanet bool
	AttackFromNearestMoon bool
	DeleteCombatReports bool
	Planet BotPlanet
}
type ServerID int64
